language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - mkdir -p build/logs
  - phpunit

after_script:
  - php vendor/bin/phpcov merge --clover build/logs/clover.xml --whitelist src build/coverage
  - php vendor/bin/coveralls
